mes_crud:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

vote:
    path:     /vote
    defaults: { _controller: AppBundle:Default:vote }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

article:
    path:     /article/{id}
    defaults: { _controller: AppBundle:Default:article }
    methods:  [GET, POST]