epreuve:
    path:     /
    defaults: { _controller: "AppBundle:Epreuve:index" }

epreuve_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Epreuve:show" }

epreuve_new:
    path:     /new
    defaults: { _controller: "AppBundle:Epreuve:new" }

epreuve_create:
    path:     /create
    defaults: { _controller: "AppBundle:Epreuve:create" }
    methods:  POST

epreuve_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Epreuve:edit" }

epreuve_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Epreuve:update" }
    methods:  [POST, PUT]

epreuve_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Epreuve:delete" }
    methods:  [POST, DELETE]
